azure:
    cosmos:
        database: traveldb-taua-prd
        key: ${COSMOS_TAUA_KEY}
        queryMetricsEnabled: true
        secondaryKey: ${COSMOS_TAUA_SECONDARY_KEY}
        uri: https://traveldb-taua.documents.azure.com:443/

spring:
    rabbitmq:
        host: rmq-pro-taua.aks-internal.io
        port: 5672
        virtual-host: /taua
        username: taua-user
        password: ${RABBITMQ_TAUA_PASSWORD}

mandrill:
    key: ${MANDRILL_API_KEY}

bugsnag:
    release-stage: ${OMNI_ENV}

logging:
    file:
        path: "/tmp/emails-core-logs"

---
spring:
    config:
        activate:
            on-profile: dev
    rabbitmq:
        host: rmq-qa.aks-internal.io
        port: 5672
        virtual-host: /taua
        username: taua-user
        password: ${RABBITMQ_TAUA_PASSWORD}

azure:
    cosmos:
        database: traveldb-taua
        key: ${COSMOS_TAUA_KEY_SANDBOX}
        queryMetricsEnabled: true
        secondaryKey: ${COSMOS_TAUA_SECONDARY_KEY_SANDBOX}
        uri: https://traveldb-taua-dev-v3.documents.azure.com:443/