azure:
    cosmos:
        database: traveldb-taua
        key: ${COSMOS_TAUA_KEY}
        queryMetricsEnabled: true
        secondaryKey: ${COSMOS_TAUA_SECONDARY_KEY}
        uri: https://traveldb-taua.documents.azure.com:443/

spring:
    rabbitmq:
        host: rmq-qa.aks-internal.io
        port: 5672
        virtual-host: /taua
        username: taua-user
        password: zvXaE3A43y8zc7jb
    mail:
        default-encoding: UTF-8
        host: smtp.mandrillapp.com
        password: Vmn_hcxppJrqjFlbvfgWiQ
        port: 587
    properties:
        mail:
            smtp:
                auth: true
                enable: true
        protocol: smtp
        test-connection: false
        username: techadmin@omnilogic.com.br

mandrill:
    key: ${MANDRILL_API_KEY}

bugsnag:
    release-stage: ${OMNI_ENV}

---
spring:
    config:
        activate:
            on-profile: dev

azure:
    cosmos:
        database: traveldb-taua
        key: ${COSMOS_TAUA_KEY_SANDBOX}
        queryMetricsEnabled: true
        secondaryKey: ${COSMOS_TAUA_SECONDARY_KEY_SANDBOX}
        uri: https://traveldb-taua-dev-v3.documents.azure.com:443/