FROM openjdk:18-jdk-alpine

ENV TZ=America/Fortaleza
USER root
RUN apk update && apk add tzdata
ENTRYPOINT echo "Server datetime is: $(date +'%d/%m/%Y %H:%m:%S')"

COPY /target/TravelEmailsCore.jar /TravelEmailsCore.jar