apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    budy/pipeline: https://ci.omnilogic.com.br/omnilogic/integrationvoluxapi/pipelines/pipeline/480
    git.repo: https://github.com/OmniLogic/IntegrationVoluxAPI
  name: travel-taua-emails-consumer
  namespace: integrations
spec:
  selector:
    matchLabels:
      app: travel-taua-emails-consumer
  template:
    metadata:
      labels:
        app: travel-taua-emails-consumer
    spec:
      containers:
      - command:
        - java
        - -jar
        - TravelEmailsCore.jar
        env:
        - name: OMNI_ENV
          value: prd
        - name: COSMOS_TAUA_KEY
          valueFrom:
            secretKeyRef:
              key: COSMOS_TAUA_KEY
              name: integrations-secret
        - name: COSMOS_TAUA_SECONDARY_KEY
          valueFrom:
            secretKeyRef:
              key: COSMOS_TAUA_SECONDARY_KEY
              name: integrations-secret
        - name: COSMOS_TAUA_KEY_SANDBOX
          valueFrom:
            secretKeyRef:
              key: COSMOS_TAUA_KEY_SANDBOX
              name: integrations-secret
        - name: COSMOS_TAUA_SECONDARY_KEY_SANDBOX
          valueFrom:
            secretKeyRef:
              key: COSMOS_TAUA_SECONDARY_KEY_SANDBOX
              name: integrations-secret
        - name: MANDRILL_API_KEY
          valueFrom:
            secretKeyRef:
              key: MANDRILL_API_KEY
              name: integrations-secret
        image: omnilogic.azurecr.io/travel-taua-emails-queue-consumer:v0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - '[ -n "$(find /tmp/integration-volux-logs/*log* -mmin -30)" ] || exit
              1'
        name: travel-taua-emails-consumer
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 300m
            memory: 1Gi
